<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-23T18:22:13 IST" name="Default suite" finished-at="2025-04-23T18:22:24 IST" duration-ms="11484">
    <groups>
    </groups>
    <test started-at="2025-04-23T18:22:13 IST" name="Default test" finished-at="2025-04-23T18:22:24 IST" duration-ms="11484">
      <class name="testCases.failedss">
        <test-method signature="Setup()[pri:1, instance:testCases.failedss@6302bbb1]" started-at="2025-04-23T18:22:13 IST" name="Setup" finished-at="2025-04-23T18:22:17 IST" duration-ms="4664" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method is-config="true" signature="tearDown1(org.testng.ITestResult)[pri:0, instance:testCases.failedss@6302bbb1]" started-at="2025-04-23T18:22:17 IST" name="tearDown1" finished-at="2025-04-23T18:22:17 IST" duration-ms="6" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Setup status=SUCCESS method=failedss.Setup()[pri:1, instance:testCases.failedss@6302bbb1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown1 -->
        <test-method signature="Forgot_Password()[pri:2, instance:testCases.failedss@6302bbb1]" started-at="2025-04-23T18:22:17 IST" name="Forgot_Password" finished-at="2025-04-23T18:22:23 IST" duration-ms="5995" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://kinda.jcsoftwaresolution.in/otp-verifyy] but found [https://kinda.jcsoftwaresolution.in/otp-verify]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://kinda.jcsoftwaresolution.in/otp-verifyy] but found [https://kinda.jcsoftwaresolution.in/otp-verify]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.failedss.Forgot_Password(failedss.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Forgot_Password -->
        <test-method is-config="true" signature="tearDown1(org.testng.ITestResult)[pri:0, instance:testCases.failedss@6302bbb1]" started-at="2025-04-23T18:22:23 IST" name="tearDown1" finished-at="2025-04-23T18:22:24 IST" duration-ms="536" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Forgot_Password status=FAILURE method=failedss.Forgot_Password()[pri:2, instance:testCases.failedss@6302bbb1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown1 -->
        <test-method is-config="true" signature="tearDownReport()[pri:0, instance:testCases.failedss@6302bbb1]" started-at="2025-04-23T18:22:24 IST" name="tearDownReport" finished-at="2025-04-23T18:22:24 IST" duration-ms="242" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownReport -->
      </class> <!-- testCases.failedss -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
